version: "3.8"

networks:
  dev:

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    networks:
      - dev

  bot:
    build:
      context: ./bot
      dockerfile: Dockerfile
    volumes:
      - .:/app
    depends_on:
      - api
    networks:
      - dev

